name: dart_katla_image
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  ffigen: ^2.2.2
  image: ^3.0.1
  intl: ^0.17.0
  benchmark_harness: any

ffigen:
  name: 'ImageBinding'
  llvm-lib: '/usr/lib'
  output: 'lib/src/image_ffi.dart'
  headers:
    entry-points:
      - '../katla/image/c-api/image.h'
      - '../katla/dart/c-api/dart-image.h'
  compiler-opts: '-I../katla/'
